### ISSUE TITLE
Add multiprocessing code for speed-up

### ISSUE THREAD

**Issue by danellecline** [mbari-org/voc-cropper#4]
For speed-up!  Fan-out by file.

Inspiration from the wav metadata code:

https://github.com/mbari-org/soundscape-wavdata/blob/main/metadata/run.py

```
    import multiprocessing
 
    with multiprocessing.Pool(num_processes) as pool:
        days = (end - start).days
        args = [(args.wav_path, args.metadata_path, args.search, start + timedelta(days=i)) for i in range(days)]
        pool.starmap(MetadataGenerator, args)
```

**Comment by carueda** [comment]
Cool. When this is incorporated it would be interesting to do some comparison with https://github.com/mbari-org/blaise ⏳
